GERAL_DOC_TROCA_CARGO
GP-2020-9L/9Lives pull request #10
Opened 2020-11-26 15:20 UTC by luizasalmeida

2020-11-26 15:32 UTC, SofiaLebreiro requested changes
Erro ortografico na descrição "deverao"

2020-11-26 18:13 UTC, KOWalter commented on doc/Gestao/GERAL_DOC_TROCA_CARGO.md
> +Neste ficheiro dererão ficar indicadas todas as mudanças de troca de cargo existentes ao longo da realização do projeto.
Erro ortográfico no deverão, está escrito "dererão"

2020-11-26 18:13 UTC, KOWalter commented on doc/Gestao/GERAL_DOC_TROCA_CARGO.md
> +|---|---|---|---|---|
Talvez retirar esta linha da tabela

2020-12-14 17:10 UTC, SofiaLebreiro approved these changes

2020-12-14 17:10 UTC, SofiaLebreiro approved these changes

2020-12-14 17:11 UTC, merged