GERAL_ATA_INTERNA#6
GP-2020-9L/9Lives pull request #9
Opened 2020-11-22 18:05 UTC by luizasalmeida

2020-11-26 15:15 UTC, SofiaLebreiro requested changes
O documento de troca de cargos ainda nao foi feito. Nao pode estar na secção tarefas realizadas

2020-11-26 18:16 UTC, KOWalter requested changes

2020-11-26 18:16 UTC, KOWalter commented on doc/Atas/GERAL_ATA_INTERNA#6.md
> +0.2 | Luiza Almeida | correção da última conclusão |
Faltou a data

2020-12-14 17:17 UTC, SofiaLebreiro approved these changes

2020-12-14 17:17 UTC, merged